### ISSUE TITLE
Link invite redirect to main 

### ISSUE THREAD

**Issue by ernesst** [strukturag/nextcloud-spreedme#48]
I've post my issue already on owncloud app website, but for a better tracking i share it here : 

Thanks for this great app. 

I've notice two issues when i'm sharing a room link. 
- when i click on the link icon to display the link i see : /index.php/apps/spreedme#conf/test_room but the url associated is correct. 
- When i'm generating a code to invite somebody the URL it looks like https://Mydmaine.org/index.php/apps/spreedme?tp=XXXXXXXXXXXXXXXXX%3D%3D#conf%2Ftest_room
  This link brings me only to the main room, it seems to not find the conf/test_room.
  then when the guest wrote conf/test_room in the box he is joining us without problem. 
  When do you think could come from the issue ? 

Regards

**Comment by leonklingele** [comment]
> when i click on the link icon to display the link i see : /index.php/apps/spreedme#conf/test_room but the url associated is correct.

This was fixed with 136e160a83a8928ea821145885aff114ceba0974

> This link brings me only to the main room

Are you sure? It works fine work me.
Can you try to reproduce it again using another room name (e.g. `test`)?

**Comment by ernesst** [comment]
Thanks for the fix,
I just clone the git master to be sure and same results even with test, i'm redirected to the "waiting room"

**Comment by bitking** [comment]
@leonklingele I just updated the app but i still not get the associated URL (FQDN) with your fix.

**Comment by leonklingele** [comment]
Hi @bitking,

I haven’t made a new release of the app which includes this fix.
If you want to try it, either manually apply the patch or clone
this git repo and switch to the `develop` branch.

**Comment by bitking** [comment]
@leonklingele thanks i was oblivious to this, now it works.

**Comment by leonklingele** [comment]
@ernesst I still can't reproduce the second issue you've described (room not joined when invitation link is used). Can you please provide further information about your setup (browser version, etc.)?

**Comment by ernesst** [comment]
Sorry for the late answer, 

On my ubuntu laptop or my windows working laptop whatever i use chrome or firefox the result is the same.

Is there a way to generate log ?

**Comment by leonklingele** [comment]
> Is there a way to generate log ?

Yes, please follow these steps:
1. Open the Spreed.ME app in Nextcloud
2. Append `?debug#test123` to the URL (apps/spreedme/?debug#test123)
3. Open your browser’s developer console
4. Post the output of it (replace sensitive values)

**Comment by leonklingele** [comment]
Any news on this @ernesst ?

**Comment by ernesst** [comment]
Thanks for the reminder, 

When i enter the URL https://myserver/index.php/apps/spreedme/?debug#test123
the loaded page has the URL https://myserver/index.php/apps/spreedme/?debug#

the output : 
```
GET 
https://myserver/index.php/apps/spreedme/ [HTTP/1.1 200 OK 96ms]
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.(unknown)
GET 
https://myserver/core/vendor/handlebars/handlebars.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/backbone/backbone.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/oc-dialogs.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/js.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/l10n.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/octemplate.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/eventsource.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/config.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/search/js/search.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/oc-requesttoken.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/apps.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/mimetype.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/mimetypelist.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/snapjs/dist/latest/snap.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/oc-backbone.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/placeholder.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/jquery.avatar.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/delete_confirmation/js/bind_first.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/delete_confirmation/js/script_version9.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/files_pdfviewer/js/previewplugin.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/shareconfigmodel.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/shareitemmodel.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/sharedialogresharerinfoview.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/sharedialoglinkshareview.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/sharedialogmailview.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/sharedialogexpirationview.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/sharedialogshareelistview.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/sharedialogview.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/share.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/firstrunwizard/js/jquery.colorbox.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/firstrunwizard/js/firstrunwizard.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/files/fileinfo.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/files/client.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/index.php/apps/theming/js/theming [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/styles.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/inputs.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/header.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/icons.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/fonts.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/apps.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/global.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/fixes.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/multiselect.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/mobile.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/jquery-ui/themes/base/jquery-ui.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/jquery-ui-fixes.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/tooltip.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/files_pdfviewer/css/style.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/share.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/files_versions/css/versions.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/firstrunwizard/css/colorbox.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/firstrunwizard/css/firstrunwizard.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/notifications/css/styles.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/css/jquery.ocdialog.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/spreedme/css/webrtc.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/index.php/core/js/oc.js [HTTP/1.1 200 OK 72ms]
GET 
https://myserver/core/vendor/jquery/dist/jquery.min.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/jquery-migrate/jquery-migrate.min.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/jquery-ui/ui/jquery-ui.custom.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/underscore/underscore.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/moment/min/moment-with-locales.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/blueimp-md5/js/md5.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/bootstrap/js/tooltip.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/es6-promise/dist/es6-promise.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/davclient.js/lib/client.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/vendor/clipboard/dist/clipboard.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/placeholders.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/compatibility.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/core/js/jquery.ocdialog.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/notifications/js/app.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/notifications/js/notification.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/spreedme/extra/static/PostMessageAPI.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/apps/spreedme/js/webrtc.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/index.php/apps/direct_menu/styles [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/index.php/apps/theming/styles [HTTP/1.1 200 OK 0ms]
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar’.  Ruleset ignored due to bad selector.styles.css:84:2
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar-track-piece’.  Ruleset ignored due to bad selector.styles.css:87:2
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar-thumb’.  Ruleset ignored due to bad selector.styles.css:90:2
Unknown property ‘user-select’.  Declaration dropped.styles.css:141:12
Unknown property ‘user-select’.  Declaration dropped.styles.css:272:12
Unknown property ‘user-select’.  Declaration dropped.styles.css:313:12
Unknown property ‘user-select’.  Declaration dropped.styles.css:374:12
Unknown property ‘user-select’.  Declaration dropped.styles.css:418:12
Unknown property ‘list-style-indent’.  Declaration dropped.styles.css:421:87
Unknown property ‘appearance’.  Declaration dropped.inputs.css:208:11
Expected media feature name but found ‘-webkit-max-device-pixel-ratio’.fonts.css:2:8
Unknown property ‘user-select’.  Declaration dropped.apps.css:30:12
Expected color but found ‘top’.  Error in parsing value for ‘background-image’.  Declaration dropped.apps.css:136:35
Error in parsing value for ‘background-image’.  Declaration dropped.apps.css:138:19
Error in parsing value for ‘text-overflow’.  Declaration dropped.apps.css:270:17
Unknown property ‘-moz-filter’.  Declaration dropped.apps.css:295:12
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.apps.css:332:9
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.apps.css:338:9
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.apps.css:642:9
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.apps.css:649:9
Unknown property ‘-moz-box-shadow’.  Declaration dropped.multiselect.css:22:16
Error in parsing value for ‘display’.  Declaration dropped.mobile.css:23:10
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:49:8
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:538:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:918:8
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:925:8
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:929:8
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:1177:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.jquery-ui.css:1184:9
Unknown property ‘line-break’.  Declaration dropped.tooltip.css:14:12
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.tooltip.css:27:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.tooltip.css:31:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.versions.css:18:9
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.versions.css:30:9
Error in parsing value for ‘margin’.  Declaration dropped.colorbox.css:10:18
JQMIGRATE: Migrate is installed, version 1.4.0jquery-migrate.min.js:2:542
Unknown property ‘-moz-border-radius’.  Declaration dropped.styles:108:20
Unknown property ‘-moz-filter’.  Declaration dropped.styles:117:13
GET 
https://myserver/core/vendor/backbone/backbone.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/ [HTTP/1.1 200 OK 6ms]
GET 
https://myserver/index.php/avatar/USER/32 [HTTP/1.1 200 OK 122ms]
GET 
XHR 
https://myserver/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 115ms]
GET 
https://myserver/webrtc/static/ver=0293/css/bootstrap.min.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/static/ver=0293/css/font-awesome.min.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/static/ver=0293/css/main.min.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/extra/static/ver=0293/css/owncloud.css [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/static/ver=0293/js/libs/require/require.js [HTTP/1.1 200 OK 0ms]
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.bootstrap.min.css:1:139
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.bootstrap.min.css:1:1443
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.bootstrap.min.css:1:1683
Unknown property ‘orphans’.  Declaration dropped.bootstrap.min.css:1:2482
Unknown property ‘widows’.  Declaration dropped.bootstrap.min.css:1:2491
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.bootstrap.min.css:1:3458
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.bootstrap.min.css:1:12734
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.bootstrap.min.css:1:12867
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.bootstrap.min.css:1:13179
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘margin-top’.  Declaration dropped.bootstrap.min.css:1:32492
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.bootstrap.min.css:1:32746
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.bootstrap.min.css:1:33675
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.bootstrap.min.css:1:33723
Expected end of value but found ‘�’.  Error in parsing value for ‘line-height’.  Declaration dropped.bootstrap.min.css:1:34095
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘margin-top’.  Declaration dropped.bootstrap.min.css:1:36647
Unknown property ‘user-select’.  Declaration dropped.bootstrap.min.css:1:45258
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.bootstrap.min.css:1:45343
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:45712
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:53904
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:58692
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.bootstrap.min.css:1:78728
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:80889
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:81999
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:82657
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:83321
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:83983
Unknown property ‘zoom’.  Declaration dropped.bootstrap.min.css:1:84386
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:98927
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:99036
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:100171
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:100225
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:101230
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:101277
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.bootstrap.min.css:1:104746
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:105275
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:105507
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:105698
Error in parsing value for ‘background-image’.  Declaration dropped.bootstrap.min.css:1:105960
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:106151
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.bootstrap.min.css:1:106370
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘background-color’.  Declaration dropped.bootstrap.min.css:1:107330
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.font-awesome.min.css:4:586
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.font-awesome.min.css:4:1773
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.font-awesome.min.css:4:1992
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.font-awesome.min.css:4:2216
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.font-awesome.min.css:4:2445
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.font-awesome.min.css:4:2662
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.main.min.css:20:518
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.main.min.css:20:720
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.main.min.css:20:1605
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.main.min.css:20:1756
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.main.min.css:20:5340
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.main.min.css:20:6662
Unknown pseudo-class or pseudo-element ‘-webkit-full-screen’.  Ruleset ignored due to bad selector.main.min.css:20:6974
Unknown pseudo-class or pseudo-element ‘-ms-fullscreen’.  Ruleset ignored due to bad selector.main.min.css:20:7045
Unknown pseudo-class or pseudo-element ‘fullscreen’.  Ruleset ignored due to bad selector.main.min.css:20:7077
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:9448
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar’.  Ruleset ignored due to bad selector.main.min.css:20:9752
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar’.  Ruleset ignored due to bad selector.main.min.css:20:9854
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar-thumb’.  Ruleset ignored due to bad selector.main.min.css:20:9995
Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar-thumb’.  Ruleset ignored due to bad selector.main.min.css:20:10059
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:10917
Unknown property ‘touch-callout’.  Declaration dropped.main.min.css:20:12714
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:12799
Error in parsing value for ‘box-shadow’.  Declaration dropped.main.min.css:20:14462
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:18903
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:23757
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:33693
Error in parsing value for ‘background’.  Declaration dropped.main.min.css:20:34113
Unknown property ‘user-select’.  Declaration dropped.main.min.css:20:36636
Error in parsing value for ‘-webkit-perspective’.  Declaration dropped.main.min.css:20:36974
Error in parsing value for ‘perspective’.  Declaration dropped.main.min.css:20:36991
Error in parsing value for ‘max-height’.  Declaration dropped.main.min.css:20:43977
Error in parsing value for ‘text-align’.  Declaration dropped.main.min.css:20:45003
Unknown pseudo-class or pseudo-element ‘-webkit-slider-thumb’.  Ruleset ignored due to bad selector.main.min.css:20:50136
Expected pseudo-element but found ‘-moz-focusring’.  Ruleset ignored due to bad selector.main.min.css:20:50395
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.main.min.css:20:51101
GET 
https://myserver/webrtc/static/ver=0293/img/bg-tiles.jpg [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/extra/static/ver=0293/img/logo.svg [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/static/ver=0293/fonts/fontawesome-webfont.woff [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/static/ver=0293/js/main.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/static/ver=0293/js/base.js [HTTP/1.1 200 OK 0ms]
Launching ...main.js:47:1726
Web fonts loaded.main.js:47:867
GET 
https://myserver/webrtc/static/ver=0293/js/app.js [HTTP/1.1 200 OK 0ms]
GET 
https://myserver/webrtc/extra/static/owncloud.js [HTTP/1.1 200 OK 0ms]
Enabled mediaDevices adapter ...app.js:241:12343
Browser support for filesystem API not found.app.js:243:6139
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.webrtc:1:291
GET 
https://myserver/webrtc/extra/static/PostMessageAPI.js [HTTP/1.1 200 OK 0ms]
Selected language: enapp.js:253:30752
Bootstrapping ...main.js:47:1635
App runtime id: kgtgdixapp.js:242:5768
Service version: 0.29.3app.js:242:1676
Ws URL: wss://myserver/webrtc/wsapp.js:242:1711
Secure Contextual Escaping: trueapp.js:242:1737
Initializing ...app.js:253:29559
PostMessageAPI: POSTING FROM Location → https://myserver/webrtc/ "TO https://myserver" Object { type: "init" }PostMessageAPI.js:50:3
Screensharing support true app.js:244:5366
Initial room path set, continuing to connect ...app.js:242:4260
Ready to connect ...app.js:242:4064
Checking for media access ...app.js:246:17774
Continue with connect after media check ...app.js:246:17404
‘mozHidden’ and ‘mozVisibilityState’ are deprecated.  Please use the unprefixed ‘hidden’ and ‘visibilityState’ instead.base.js:260:13747
Initializing complete.app.js:253:29638
Connecting ...app.js:242:3794
Created new video layout renderer invisible Object {  }app.js:243:21644
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://myserver", lastEventId: "", source: Window → spreedme, ports: MessagePortList, currentTarget: Window → webrtc, eventPhase: 2, bubbles: false, cancelable: false }PostMessageAPI.js:50:3
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://myserver", lastEventId: "", source: Window → spreedme, ports: MessagePortList, currentTarget: Window → webrtc, eventPhase: 2, bubbles: false, cancelable: false }PostMessageAPI.js:50:3
GET 
https://myserver/webrtc/extra/static/ver=0293/img/logo-48x48.png [HTTP/1.1 200 OK 0ms]
GET 
XHR 
https://myserver/webrtc/static/ver=0293/sounds/sprite1.ogg [HTTP/1.1 200 OK 0ms]
GET 
XHR 
https://myserver/index.php/apps/spreedme/api/v1/user/token [HTTP/1.1 200 OK 185ms]
GET 
XHR 
https://myserver/index.php/apps/spreedme/api/v1/user/config [HTTP/1.1 200 OK 91ms]
GET 
https://myserver/webrtc/ws [HTTP/1.1 101 Switching Protocols 68ms]
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://myserver", lastEventId: "", source: Window → spreedme, ports: MessagePortList, currentTarget: Window → webrtc, eventPhase: 2, bubbles: false, cancelable: false }PostMessageAPI.js:50:3
GET 
https://myserver/index.php/avatar/USER/256 [HTTP/1.1 200 OK 96ms]
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://myserver", lastEventId: "", source: Window → spreedme, ports: MessagePortList, currentTarget: Window → webrtc, eventPhase: 2, bubbles: false, cancelable: false }PostMessageAPI.js:50:3
Connector on connection open.app.js:240:1125
TURN servers selected:  Array [ "turn:MYSERVER:8443?transpo…" ] 3600 Array [  ]app.js:244:21404
OC: selfReceived Object { Type: "Self", Id: "", Sid: "", Userid: "", Suserid: "", Token: "", Version: "0.29.3", ApiVersion: 1.4, Turn: Object, Stun: Array[0] }owncloud.js:86:3
PATCH 
XHR 
https://myserver/webrtc/api/v1/sessions/CdyJq3B3otwDM0lSg9WKSyrFBqcwlZ8Vp1xZTXsXmgp8PT1RdEpareztzerZERTZERGSDFG4545TZDFG245TRTGHZNY196R3I0VHlwS21CNDF4bFVncndISVB0anNmZnpoT0pGYXF1fDQzODM3ODk3NDE=/ [HTTP/1.1 404 Not Found 4ms]
TURN servers selected:  Array [ "turn:hytte.duckdns.org:8443?transpo…" ] 3600 Array [  ]app.js:244:21404
OC: Failed to authorize session 404 404 page not found
owncloud.js:86:3
Joining room Array [ "" ]app.js:244:11589
Error: modal.find(...).scope(...) is undefined
.initialize/</doLogin/</</<@https://myserver/webrtc/extra/static/owncloud.js:355:21
o/c<@https://myserver/webrtc/static/ver=0293/js/main.js:43:30225
o@https://myserver/webrtc/static/ver=0293/js/main.js:42:4815
He/c.defer/n<@https://myserver/webrtc/static/ver=0293/js/main.js:42:6267
main.js:43:9383

PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://myserver", lastEventId: "", source: Window → spreedme, ports: MessagePortList, currentTarget: Window → webrtc, eventPhase: 2, bubbles: false, cancelable: false }PostMessageAPI.js:50:3
Joined room Array [ "" ]app.js:244:11867
Joined room Object { Type: "Room", Name: "", Credentials: null } CdyJq3B3otwDM0lSg9WKSyrFBqcwlR3I0VHlwS21CNDF4bFVncndISVB0anNmZnpoT0pGYXF1fDQzODM3ODk3NDE=app.js:241:21326
PostMessageAPI: POSTING FROM Location → https://myserver/webrtc/ "TO https://myserver" Object { type: "roomChanged", roomChanged: "" }PostMessageAPI.js:50:3
Create new chatroom Array [ "" ]app.js:246:2369
GET 
XHR 
https://myserver/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 107ms]
GET 
XHR 
https://myserver/ocs/v2.php/apps/notifications/api/v1/notifications [HTTP/1.1 200 OK 173ms]
GET 
XHR 
https://myserver/ocs/v2.php/apps/notifications/api/v1/notifications
```

**Comment by leonklingele** [comment]
> When i enter the URL https://myserver/index.php/apps/spreedme/?debug#test123
> the loaded page has the URL https://myserver/index.php/apps/spreedme/?debug#

Why does it remove `test123`? What happens if you add it again and reload the page?
It logs `OC: Failed to authorize session` which indicates that your spreed-webrtc secret doesn’t make the one configured for the NC app. Please make sure you use the same shared secret :)
Which version of the app and Spreed WebRTC are you running?
Can you please share your Spreed WebRTC config?

**Comment by ernesst** [comment]
Good catch, I forgot to move the config file after upgrade of the server, thanks. 

I don't know why it remove test123, it's my second bullet point on my initial post. 

/var/www/html/nextcloud/apps/spreedme/config/config.php
```

 *
 * This file is licensed under the Affero General Public License version 3 or
 * later. See the COPYING file.
 *
 * @author Leon <leon@struktur.de>
 * @copyright struktur AG 2016
 */

namespace OCA\SpreedME\Config;

class Config {

        // Domain of your Spreed WebRTC server (including protocol and optional port number), examples:
        //const SPREED_WEBRTC_ORIGIN = 'https://mynextcloudserver.com';
        //const SPREED_WEBRTC_ORIGIN = 'https://webrtc.mynextcloudserver.com:8080';


        // If this is empty or only includes a port (e.g. :8080), host will automatically be determined (current host)
        const SPREED_WEBRTC_ORIGIN = 'https://MYSERVER';

        // This has to be the same `basePath`
        // you already set in the [http] section of the `server.conf` file from Spreed WebRTC server
        const SPREED_WEBRTC_BASEPATH = '/webrtc/';

        // This has to be the same `sharedsecret_secret` (64-character HEX string)
        // you already set in the [users] section of the `server.conf` file from Spreed WebRTC server
        const SPREED_WEBRTC_SHAREDSECRET = 'MYKEY';

        // Set to true if at least one another Nextcloud instance uses the same Spreed WebRTC server
        const SPREED_WEBRTC_IS_SHARED_INSTANCE = false;

        // Set to true if you want to allow access to this app + spreed-webrtc for non-registered users who received a temporary password by an Nextc$
        // You can generate such a temporary password at: /index.php/apps/spreedme/admin/tp (Nextcloud admin user account required)
        const OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED = true;

        // If 'OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED' is set to true, you also have to provide a signing key here (64-character HEX string)
        // Generate it using `xxd -ps -l 32 -c 32 /dev/random` (better) or `openssl rand -hex 32`
        const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY = 'MYKEY';

        private function __construct() {

        }

```


spreed-webrtc-server -v
Version 0.29.3

Version Coturn-4.5.0.3 'dan Eider'

 Spreed.ME 0.3.3

**Comment by ernesst** [comment]
If i enter test123 in the box and clic at the icon, then the URL shows https://myserver/index.php/apps/spreedme?debug#test123

**Comment by leonklingele** [comment]
Can you please post your browser console output again — just to be sure that there’s no other problem.
Does this hash-problem also occur on other websites? Can you please open https://www.w3.org/test123?debug#test123 and verify that `#test123` is not removed?

**Comment by ernesst** [comment]
I've rebooted my server, i might forget to restart a service between apache / webrtc / coturn. 
Now everything works fine account + guest room redirection, you pined point the problem : a shared secret key was not matching between the config files. 

Thanks
