### ISSUE TITLE
WebRTC API config endpoint does not include a plugin

### ISSUE THREAD

**Issue by k0sebamse** [strukturag/nextcloud-spreedme#72]
Hi,

when I run the tests the 3rd test is failing (Message: WebRTC API config endpoint does not include a plugin). What does that exactly mean? I googled it and only found the PHP-files here in the repository.

I run spreedme on Ubuntu 14.04, Apache 2.4.7 and PHP 7.0.15 (Opcache enabled) and Nextcloud 11.0.1

What I did:
- Installed spreed-webrtc from the repository
- downloaded the app and enabled it
- generated the config for webrtc
- modified the Apache config
- copied and modified extra/static/config/OwnCloudConfig.js (set to protocol, host and port)
- restart apache and webrtc

My webrtc-config:
```
[http]
listen = 127.0.0.1:8090
basePath = /webrtc/
root = /usr/share/spreed-webrtc-server/www

[app]
sessionSecret = xxx
encryptionSecret = yyy
authorizeRoomJoin = true
serverToken = zzz
serverRealm = local
extra = [path to nextcloud]/apps/spreedme/extra
plugin = extra/static/owncloud.js

[users]
enabled = true
mode = sharedsecret
sharedsecret_secret = aaa
```
My apache config:
```
#Spreed
		<Location /webrtc>
			ProxyPass http://127.0.0.1:8090/webrtc
			ProxyPassReverse /webrtc
		</Location>

		<Location /webrtc/ws>
			ProxyPass ws://127.0.0.1:8090/webrtc/ws
		</Location>

		ProxyVia On
		ProxyPreserveHost On
		RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
```

The webrtc log looks normal to me:
```
server 2017/01/30 22:27:49 Starting HTTP server on 127.0.0.1:8090
server 2017/01/30 22:29:31 Using '/webrtc/' base base path.
server 2017/01/30 22:29:31.538538 Enabled modules: [screensharing youtube presentation contacts]
server 2017/01/30 22:29:31.539804 Loaded extra templates from: [nextcloud-path]/apps/spreedme/extra
server 2017/01/30 22:29:31.539922 Using the number of CPU's (8) as GOMAXPROCS
server 2017/01/30 22:29:31.539942 Max open files are 4096
server 2017/01/30 22:29:31.542196 Enabled users handler 'sharedsecret'
server 2017/01/30 22:29:31.542513 Added URL handler /extra/static/... for static files in [nextcloud-path]/apps/spreedme/extra/static/...
server 2017/01/30 22:29:31 Starting HTTP server on 127.0.0.1:8090

```

The owncloud.js is available in the static folder. What am I missing?
Thank you in advance.

Regards
Mirco

**Comment by leonklingele** [comment]
On which external port is Spreed WebRTC available? (i.e. into which `VirtualHost` of Apache did you put in the config)?
What does https://your-nextcloud.com/webrtc/api/v1/config return?

`OwnCloudConfig.js` is only required if Spreed WebRTC and Nextcloud do not run on the same host (e.g. on a different port, domain, protocol).
In most cases this file is not needed and should be deleted.

**Comment by k0sebamse** [comment]
Spreed WebRTC and the cloud are available on the same domain: cloud.kosebamse.com
I added the config to the Virtualhost config of my cloud.

Output of the URL:

> {
>   "Title": "Spreed WebRTC",
>   "S": "static/ver=0281",
>   "B": "/webrtc/",
>   "Token": "xxx",
>   "Renegotiation": false,
>   "StunURIs": [],
>   "TurnURIs": [],
>   "Tokens": false,
>   "Version": "0.28.1",
>   "UsersEnabled": true,
>   "UsersAllowRegistration": false,
>   "UsersMode": "sharedsecret",
>   "DefaultRoomEnabled": true,
>   "Plugin": "extra/static/owncloud.js",
>   "AuthorizeRoomCreation": false,
>   "AuthorizeRoomJoin": true,
>   "Modules": [
>     "screensharing",
>     "youtube",
>     "presentation",
>     "contacts"
>   ]
> }

My understanding was the same that I don't need it (as Cloud and WebRTC run on the same domain and port) but as it was not working it was one of the things I tried out to fix it.

**Comment by leonklingele** [comment]
The issue was fixed with ff71103cb1c83c1d11fdb97d85bac632fc5f7138.

> Spreed WebRTC and the cloud are available on the same domain

The actual issue is that you include `:443` (default port for https) in `OWNCLOUD_ORIGIN`. This is something we currently do not support.
So either delete `OwnCloudConfig.js` or remove `:443` and everything should work fine.

**Comment by k0sebamse** [comment]
Hi,

I fixed it, it is working now. Thanks a lot for your support. Having a conference on my LAN works, but not over the Internet. So looks I must deal with coturn now.

Cheers
Mirco

**Comment by k0sebamse** [comment]
Update: sorry, forgot to run the checks... apps/spreedme/admin/debug still shows test3 failing. But why was it then working on my LAN?
```

Spreed.ME Version 0.3.6

Ran test #1 (testOwncloudPhpConfigFile):
   Passed without an error

Ran test #2 (testOwncloudJavascriptConfigFile):
   Passed without an error

Ran test #3 (testSpreedWebRTCAPI):
   Error: WebRTC API config endpoint does not include a plugin

Some tests failed. :( 
```

**Comment by leonklingele** [comment]
Because you likely didn't apply ff71103cb1c83c1d11fdb97d85bac632fc5f7138 by yourself. The fix will be included in the next release.

**Comment by k0sebamse** [comment]
Hi,

sorry for the late reply. It is working now perfectly.
Thanks a lot for your support.

Cheers
Mirco
